export const techStacks = {
  'Frontend developer': [
    'HTML',
    'CSS',
    'JavaScript',
    'TypeScript',
    'React',
    'Vue',
    'Angular',
    'Svelte',
    'Tailwind CSS',
    'Bootstrap',
    'Material UI',
    'Next.js',
    'GSAP',
    'Framer Motion',
    'Vite',
    'Webpack',
    'Redux',
    'Zustand',
    'Jest',
    'Cypress',
    'Others',
  ],
  'Backend developer': [
    'Node.js',
    'Express.js',
    'NestJS',
    'PHP',
    'Laravel',
    'Ruby on Rails',
    'Django',
    'Flask',
    'Java',
    'Spring Boot',
    'Go',
    'FastAPI',
    'Koa',
    'Hapi',
    '.NET Core',
    'GraphQL',
    'REST API',
    'Others',
  ],
  'Mobile developer': [
    'React Native',
    'Flutter',
    'Dart',
    'Swift',
    'Kotlin',
    'Java',
    'Expo',
    'Xcode',
    'Android Studio',
    'Ionic',
    'NativeScript',
    'Jetpack Compose',
    'Others',
  ],
  database: [
    'MongoDB',
    'MySQL',
    'PostgreSQL',
    'SQLite',
    'Redis',
    'Cassandra',
    'Firebase',
    'DynamoDB',
    'MariaDB',
    'Others',
  ],
  'Fullstack developer': [
    'HTML',
    'CSS',
    'JavaScript',
    'TypeScript',
    'React',
    'Vue',
    'Angular',
    'Svelte',
    'Tailwind CSS',
    'Bootstrap',
    'Material UI',
    'Next.js',
    'GSAP',
    'Framer Motion',
    'Node.js',
    'Express.js',
    'NestJS',
    'PHP',
    'Laravel',
    'Ruby on Rails',
    'Django',
    'Flask',
    'Java',
    'Spring Boot',
    'Go',
    'FastAPI',
    'GraphQL',
    'MongoDB',
    'PostgreSQL',
    'MySQL',
    'Others',
  ],
  'UI/UX designer': [
    'Figma',
    'Sketch',
    'Adobe XD',
    'Framer',
    'InVision',
    'HTML/CSS',
    'JavaScript',
    'React',
    'Vue',
    'Zeplin',
    'UXPin',
    'Others',
  ],
  'DevOps developer': [
    'Docker',
    'Kubernetes',
    'Terraform',
    'Ansible',
    'Jenkins',
    'GitLab CI/CD',
    'CircleCI',
    'AWS',
    'GCP',
    'Azure',
    'Prometheus',
    'Grafana',
    'NGINX',
    'Linux',
    'Bash',
    'Others',
  ],
  'AI/ML developer': [
    'Python',
    'R',
    'Julia',
    'JavaScript',
    'TensorFlow',
    'TensorFlow.js',
    'PyTorch',
    'Scikit-learn',
    'Keras',
    'Pandas',
    'NumPy',
    'Matplotlib',
    'OpenCV',
    'Hugging Face',
    'XGBoost',
    'Others',
  ],
  'Web3 developer': [
    'Solidity',
    'JavaScript',
    'TypeScript',
    'Rust',
    'Hardhat',
    'Truffle',
    'Foundry',
    'Ethers.js',
    'Web3.js',
    'IPFS',
    'Chainlink',
    'Alchemy SDK',
    'Others',
  ],
}

export const filterTechStack = (stacks: string[]) => {
  return stacks.filter((stack) => stack.toLowerCase() !== 'others')
}

export function getTechStackForSpecialty(specialty: string) {
  if (!specialty) return []

  const normalizedSpecialty = specialty
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '_')

  const stackKeys = Object.keys(techStacks).reduce((acc, key) => {
    acc[key.toLowerCase().replace(/\s+/g, '_')] = key
    return acc
  }, {} as Record<string, string>)

  const originalKey = stackKeys[normalizedSpecialty]
  const stack = originalKey ? techStacks[originalKey as keyof typeof techStacks] : []
  return filterTechStack(stack)
}