export const techStacks = {
  frontend: [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Vue",
    "Angular",
    "TailwindCss",
    "Gsap",
    "Framer-motion",
    "Others",
  ],
  backend: [
    "Node.js",
    "Express.js",
    "PHP",
    "Laravel",
    "Ruby on Rails",
    "DJango",
    "Java",
    "Flask",
    "Others",
  ],
  mobile: [
    "React Native",
    "Flutter",
    "Dart",
    "Swift",
    "Kotlin",
    "JavaScript",
    "React",
    "Node.js",
    "Expo",
    "Andriod studio",
    "Xcode",
    "Others",
  ],
  database: ["MongoDB", "MySQL", "PostgreSQL", "SQLite", "Redis", "Others"],
  fullstack: [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Vue",
    "Angular",
    "TailwindCss",
    "Gsap",
    "Framer-motion",
    "Node.js",
    "Express.js",
    "PHP",
    "Laravel",
    "Ruby on Rails",
    "DJango",
    "Java",
    "Flask",
    "Others",
  ],
  UIUx: [
    "Figma",
    "Sketch",
    "Adobe XD",
    "HTML/CSS",
    "Javascript",
    "React",
    "Vue",
    "Others",
  ],
  DevOps: [
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Jenkins",
    "GitLab CI/CD",
    "AWS",
    "GCP",
    "Azure",
    "Others",
  ],
  AIML: [
    "Python",
    "R",
    "Julia",
    "JavaScript",
    "Tensorflow",
    "Tensorflow.js",
    "PyTorch",
    "Scikit-learn",
    "Keras",
    "Others",
  ],
  Web3: [
    'Solidity',
    'JavaScript',
    'Rust',
    'Hardhat',
    'Truffle',
    'Foundry',
    'Others'
  ]
};

export function getTechStackForSpecialty(specialty) {
  return techstacks[specialty] || [];
}
